name: Saatlik IPTV Guncelleme

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı
  workflow_dispatch:      # Manuel başlatma

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          pip install yt-dlp requests

      - name: Listeleri Olustur (Sadece Seyir Sandigi)
        run: |
          # python main.py satırı kaldırıldı
          python archive.py

      - name: Degisiklikleri Kontrol Et ve Kesin Kaydet
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Sadece seyir_sandigi dosyasını kontrol ediyoruz
          ls -la seyir_sandigi.m3u
          
          # yayinlarim.m3u buradan çıkarıldı, sadece seyir_sandigi kaldı
          git add seyir_sandigi.m3u
          
          git commit -m "Oto Guncelleme: $(date +'%Y-%m-%d %H:%M')" || echo "Degisiklik yok"
          
          git pull --rebase origin main
          git push origin main
