name: Saatlik IPTV Guncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosya yazma yetkisini buradan da zorluyoruz
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          pip install yt-dlp requests

      - name: YouTube Listesini Calistir
        run: python main.py

      - name: Seyir Sandigi Arsirini Calistir
        run: python archive.py

      - name: Dosyalari Kesin Kaydet
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Mevcut m3u dosyalarını listeye al
          git add yayinlarim.m3u seyir_sandigi.m3u
          
          # Değişiklik varsa kaydet
          git commit -m "Oto Guncelleme: $(date +'%d-%m-%Y %H:%M')" || exit 0
          
          # Zorlayarak gönder
          git push origin main --force
