name: Saatlik IPTV Guncelleme

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı otomatik çalışır
  workflow_dispatch:      # İstediğinde manuel başlatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          pip install yt-dlp requests

      - name: YouTube Listesini Calistir
        run: python main.py

      - name: Seyir Sandigi Arsirini Calistir
        run: python archive.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # Oluşan tüm m3u dosyalarını buraya ekliyoruz
          git add yayinlarim.m3u seyir_sandigi.m3u live.m3u
          git commit -m "Saatlik Guncelleme Tamamlandi" || exit 0
          git push
