name: Saatlik Guncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli kütüphaneleri yükle
        run: |
          pip install requests yt-dlp  # Buraya yt-dlp eklendi!

      - name: YouTube Listesini Calistir
        run: |
          python main.py  # YouTube listesini yapan dosya

      - name: Arsir Listesini Calistir
        run: |
          python archive.py  # Bulgaristan arşivini yapan dosya

      - name: Degisiklikleri Kaydet ve Paylas
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add live.m3u seyir_sandigi.m3u  # İki dosyayı da kaydediyoruz
          git commit -m "Saatlik otomatik guncelleme (YouTube + Arşiv)" || exit 0
          git push
